name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history and tags
          fetch-depth: 0
          fetch-tags: true
      - name: get version
        if: startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/')
        id: getVersion
        run: | # pull the version from the name of the branch.
          fullName="${{ github.head_ref }}"
          version="${fullName#*/}"
          echo "versionNumber=$version" >> $GITHUB_ENV

      - name: increment patch version
        if: startsWith(github.head_ref, 'patch/')
        id: increment_patch_version
        run: |
          # Get the latest tag, remove 'v' prefix if present
          LATEST_TAG=$(git tag --sort=-creatordate | head -n 1 | sed 's/^v//')
          echo "Latest tag: $LATEST_TAG"
          
          # Split the version number into parts
          MAJOR=$(echo $LATEST_TAG | cut -d. -f1)
          MINOR=$(echo $LATEST_TAG | cut -d. -f2)
          PATCH=$(echo $LATEST_TAG | cut -d. -f3)
          echo "Current version: $MAJOR.$MINOR.$PATCH"
          
          # Increment the patch version
          PATCH=$((PATCH + 1))
          echo "Incremented patch version: $PATCH"
          
          NEXT_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "Next version: $NEXT_VERSION"
          echo "versionNumber=$NEXT_VERSION" >> $GITHUB_OUTPUT
          echo "ENV versionNumber variable: ${{ env.versionNumber }}"


      - name: create github release
      #  if: github.head_ref == 'release/*' || github.head_ref == 'hotfix/*'
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: false
          name: ${{ env.versionNumber }}
          tag_name: ${{ env.versionNumber }}
          body: ${{ github.event.pull_request.body }}
          token: ${{ secrets.GITHUB_TOKEN }}

