name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: get version
        if: startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/')
        id: getVersion
        run: | # pull the version from the name of the branch.
          fullName="${{ github.head_ref }}"
          version="${fullName#*/}"
          echo "versionNumber=$version" >> $GITHUB_ENV

      - name: increment patch version
        if: startsWith(github.head_ref, 'patch/')
        id: increment_patch_version
        run: | # Get the latest tag from the repository and increment the patch version.
          tags=$(git tag -l | grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?$')
          latestTag=$(echo "$tags" | sort -V | tail -n 1)
          
          major=$(echo $latestTag | cut -d. -f1)
          minor=$(echo $latestTag | cut -d. -f2)
          patch=$((echo $latestTag | cut -d. -f3) + 1)
          
          nextVersion="${major}.${minor}.${patch}"
          echo "Next version: $nextVersion"
          echo "versionNumber=$nextVersion" >> $GITHUB_ENV


      - name: create github release
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          draft: false
          name: ${{ env.versionNumber }}
          tag_name: ${{ env.versionNumber }}
          body: ${{ github.event.pull_request.body }}
          token: ${{ secrets.GITHUB_TOKEN }}

