name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      #- name: Set dynamic variable
      #  run: |
      #    versionNumber="Hello, World!"
      #    echo "versionNumber=${versionNumber}" >> $GITHUB_ENV
      #    echo "${{ github.head_ref }}"
        # The variable is set for future steps in this job.
      - name: get version
        if: startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/')
        id: getVersion
        run: | # pull the version from the name of the branch.
          fullName="${{ github.head_ref }}"
          version="${fullName#*/}"
          echo "versionNumber=$version" >> $GITHUB_ENV

      - name: increment patch version
        if: startsWith(github.head_ref, 'patch/')
        id: increment_patch_version
        run: | # increment the patch version by 1. For example, if the latest tag is 1.2.3, the new version will be 1.2.4
          # get the latest tag from the repository
          latestTag=$(git describe --tags --abrev=0)
          echo "latestTag=$latestTag"

          # split the version into its components
          IFS='.' read -r major minor patch <<< "$latestTag"

          # increment the patch version
          patch=$((patch + 1))

          # create the new version string
          newVersion="$major.$minor.$patch"
          echo "versionNumber=$newVersion" >> $GITHUB_ENV


      - name: create github release
      #  if: github.head_ref == 'release/*' || github.head_ref == 'hotfix/*'
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: false
          name: "$versionNumber"
          tag_name: "$versionNumber"
          body: ${{ github.event.pull_request.body }}
          token: ${{ secrets.GITHUB_TOKEN }}


      #- name: auto increment version
      #  if: github.head_ref == 'patch/*'
      #  uses: softprops/action-gh-release@v1
      #  id: auto_increment_version
      #   with:
      #   draft: false
      #    name: ${{ steps.getVersion.outputs.versionNumber }}
      #    tag_name: ${{ steps.getVersion.outputs.versionNumber }}
      #    body: ${{ github.event.pull_request.body }}
      #    token: ${{ secrets.GITHUB_TOKEN }}

